# CD Process
name: CD

on:
  push:
    branches: [main, test]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - name: Setup pnpm
        run: npm install -g pnpm@9.1.1 && pnpm install
      - name: Setup Docker Env
        uses: docker/setup-buildx-action@v2
      - name: Run Unit Test
        run: pnpm run test:unit
      - name: Run E2E Test
        run: pnpm run test:e2e

  Build-and-Push:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t kukjun/teams-reserve-mvp:latest .
          docker push kukjun/teams-reserve-mvp:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: Build-and-Push
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/teams-reserve-mvp
            docker-compose pull
            docker-compose down
            docker-compose up -d